services:
  asterisk:
    image: andrius/asterisk
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
    volumes:
     - ./logs:/var/log/asterisk
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"